name: Regenerate RSS and JSON

# Déclencheurs
on:
  schedule:
    # Cron : tous les jours à 7h UTC (modifiable)
    - cron: '0 7 * * *'
  workflow_dispatch: # permet de lancer manuellement

jobs:
  regenerate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run generate_feed.py
      run: python generate_feed.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add feed.json rss.xml
        git diff --cached --quiet || git commit -m "Regenerate feed.json and rss.xml"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
