name: Regenerate RSS and JSON

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run: python generate_feed.py

      - name: Commit and push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main       # ou master selon ton dépôt
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
